In [4]:
import numpy as np

In [17]:
a = [i for i in range(12,24)]

In [18]:
a

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [21]:
b = np.array(a)

In [22]:
b = np.array(a, dtype = int)

In [24]:
b.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [25]:
b.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
b.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [34]:
b.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [37]:
b.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [40]:
b.reshape(-1,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [41]:
b.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [42]:
b.reshape(6,-1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [43]:
b.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [44]:
b.reshape(12,-1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [62]:
a=np.array([i for i in range(20,0,-2)])

In [63]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [64]:
b=np.array([i for i in range(20,1,-2)])

In [66]:
b.reshape(1,10)

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])