In [1]:
import numpy as np

In [3]:
a = [1,2,3,3,1,6,8,11,10,7]

In [6]:
a = np.array(a).reshape(2,5)

In [7]:
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [8]:
a = a.T

In [9]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [14]:
mean_a = np.mean(a, axis = 0)

In [15]:
mean_a

array([2. , 8.4])

In [16]:
a_centered = a - mean_a

In [17]:
a_centered.shape

(5, 2)

In [18]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

In [27]:
a_centered_sp

8.0

In [32]:
a_centered_sp/(a.shape[0]-1)

2.0

In [35]:
cov_matrix = np.cov(a.T)

In [36]:
cov_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [37]:
cov_matrix[0,1]

2.0