In [3]:
import numpy as np

In [4]:
a = [i for i in range(12,24)]

In [5]:
a

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [6]:
b = np.array(a)

In [7]:
b = np.array(a, dtype = int)

In [8]:
b.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
b.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
b.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [11]:
b.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
b.reshape(-1,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
b.reshape(-1,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
b.reshape(-1,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
b.reshape(6,-1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
b.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [22]:
a=b.reshape(12,1)

In [23]:
a.ndim

2

 значит, нельзя, тк две оси

In [26]:
a=np.random.randn(3,4)

In [27]:
a

array([[ 0.01875432, -1.46586305,  1.20962639,  1.13702992],
       [-1.24361244,  1.16444184, -3.0631342 , -0.38096548],
       [-1.03568287,  0.28848767, -0.16739699, -0.35085263]])

In [30]:
a.mean()

-0.32409729303103646

In [32]:
b=a.flatten()

In [33]:
b

array([ 0.01875432, -1.46586305,  1.20962639,  1.13702992, -1.24361244,
        1.16444184, -3.0631342 , -0.38096548, -1.03568287,  0.28848767,
       -0.16739699, -0.35085263])

In [34]:
b.ndim

1

In [35]:
a.size

12

In [36]:
b.size

12

size одинаков, размерность - 1

In [37]:
a=np.arange(20, 0, -2)

In [38]:
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [40]:
b=np.arange(20,1,-2).reshape(1,10)

In [41]:
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [42]:
a.size

10

In [43]:
b.size

10

In [46]:
a.ndim

1

In [47]:
b.ndim


2

значит, массив b - двумерный, а - одномерный

In [56]:
a = np.zeros((2,2))

In [57]:
a

array([[0., 0.],
       [0., 0.]])

In [58]:
b = np.ones((3,2))

In [59]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [61]:
v = np.vstack((a,b))

In [62]:
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [63]:
v.size

10

In [64]:
a = np.arange(12)

In [65]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
A = a.reshape(4,3)

In [67]:
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
At = A.T

In [70]:
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [71]:
B = np.dot(A, At)

In [72]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [73]:
B.size

16

In [74]:
np.linalg.det(B)

0.0

если определитель равен нулю, обратной не существует

In [75]:
np.random.seed(42)

In [76]:
c = np.random.randint(0,16,16)

In [77]:
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [78]:
c.size

16

In [79]:
C = c.reshape (4,4)

In [80]:
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [82]:
D = B+C*10

In [83]:
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [85]:
np.linalg.det(D)

-28511999.999999944

In [86]:
np.linalg.matrix_rank(D)

4

In [87]:
D_inv = np.linalg.inv(D)

In [89]:
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [90]:
D_inv[D_inv<0] = 0

In [92]:
D_inv[D_inv>0] = 1

In [93]:
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [94]:
E = np.where(D_inv, B, C)

In [95]:
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])